/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package serviceesame.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Esame service. Represents a row in the &quot;ESAME_Esame&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>serviceesame.model.impl.EsameModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>serviceesame.model.impl.EsameImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Esame
 * @generated
 */
@ProviderType
public interface EsameModel
	extends BaseModel<Esame>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a esame model instance should use the {@link Esame} interface instead.
	 */

	/**
	 * Returns the primary key of this esame.
	 *
	 * @return the primary key of this esame
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this esame.
	 *
	 * @param primaryKey the primary key of this esame
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esame ID of this esame.
	 *
	 * @return the esame ID of this esame
	 */
	public long getEsameId();

	/**
	 * Sets the esame ID of this esame.
	 *
	 * @param esameId the esame ID of this esame
	 */
	public void setEsameId(long esameId);

	/**
	 * Returns the group ID of this esame.
	 *
	 * @return the group ID of this esame
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this esame.
	 *
	 * @param groupId the group ID of this esame
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this esame.
	 *
	 * @return the company ID of this esame
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this esame.
	 *
	 * @param companyId the company ID of this esame
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this esame.
	 *
	 * @return the user ID of this esame
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this esame.
	 *
	 * @param userId the user ID of this esame
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this esame.
	 *
	 * @return the user uuid of this esame
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this esame.
	 *
	 * @param userUuid the user uuid of this esame
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this esame.
	 *
	 * @return the user name of this esame
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this esame.
	 *
	 * @param userName the user name of this esame
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this esame.
	 *
	 * @return the create date of this esame
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this esame.
	 *
	 * @param createDate the create date of this esame
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this esame.
	 *
	 * @return the modified date of this esame
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this esame.
	 *
	 * @param modifiedDate the modified date of this esame
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nome esame of this esame.
	 *
	 * @return the nome esame of this esame
	 */
	@AutoEscape
	public String getNomeEsame();

	/**
	 * Sets the nome esame of this esame.
	 *
	 * @param nomeEsame the nome esame of this esame
	 */
	public void setNomeEsame(String nomeEsame);

	/**
	 * Returns the data esame of this esame.
	 *
	 * @return the data esame of this esame
	 */
	public Date getDataEsame();

	/**
	 * Sets the data esame of this esame.
	 *
	 * @param dataEsame the data esame of this esame
	 */
	public void setDataEsame(Date dataEsame);

	/**
	 * Returns the nome insegnante of this esame.
	 *
	 * @return the nome insegnante of this esame
	 */
	@AutoEscape
	public String getNomeInsegnante();

	/**
	 * Sets the nome insegnante of this esame.
	 *
	 * @param nomeInsegnante the nome insegnante of this esame
	 */
	public void setNomeInsegnante(String nomeInsegnante);

	@Override
	public Esame cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}