/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package serviceesame.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import serviceesame.model.Esame;
import serviceesame.model.EsameModel;

/**
 * The base model implementation for the Esame service. Represents a row in the &quot;ESAME_Esame&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EsameModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EsameImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EsameImpl
 * @generated
 */
@JSON(strict = true)
public class EsameModelImpl extends BaseModelImpl<Esame> implements EsameModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a esame model instance should use the <code>Esame</code> interface instead.
	 */
	public static final String TABLE_NAME = "ESAME_Esame";

	public static final Object[][] TABLE_COLUMNS = {
		{"esameId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"nomeEsame", Types.VARCHAR},
		{"dataEsame", Types.TIMESTAMP}, {"nomeInsegnante", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("esameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("nomeEsame", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dataEsame", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("nomeInsegnante", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ESAME_Esame (esameId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,nomeEsame VARCHAR(75) null,dataEsame DATE null,nomeInsegnante VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table ESAME_Esame";

	public static final String ORDER_BY_JPQL = " ORDER BY esame.nomeEsame ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ESAME_Esame.nomeEsame ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DATAESAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NOMEESAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NOMEINSEGNANTE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EsameModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _esameId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEsameId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _esameId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Esame.class;
	}

	@Override
	public String getModelClassName() {
		return Esame.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Esame, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Esame, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Esame, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Esame)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Esame, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Esame, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Esame)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Esame, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Esame, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Esame, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Esame, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Esame, Object>>();

			attributeGetterFunctions.put("esameId", Esame::getEsameId);
			attributeGetterFunctions.put("groupId", Esame::getGroupId);
			attributeGetterFunctions.put("companyId", Esame::getCompanyId);
			attributeGetterFunctions.put("userId", Esame::getUserId);
			attributeGetterFunctions.put("userName", Esame::getUserName);
			attributeGetterFunctions.put("createDate", Esame::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Esame::getModifiedDate);
			attributeGetterFunctions.put("nomeEsame", Esame::getNomeEsame);
			attributeGetterFunctions.put("dataEsame", Esame::getDataEsame);
			attributeGetterFunctions.put(
				"nomeInsegnante", Esame::getNomeInsegnante);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Esame, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Esame, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Esame, ?>>();

			attributeSetterBiConsumers.put(
				"esameId", (BiConsumer<Esame, Long>)Esame::setEsameId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Esame, Long>)Esame::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Esame, Long>)Esame::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Esame, Long>)Esame::setUserId);
			attributeSetterBiConsumers.put(
				"userName", (BiConsumer<Esame, String>)Esame::setUserName);
			attributeSetterBiConsumers.put(
				"createDate", (BiConsumer<Esame, Date>)Esame::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Esame, Date>)Esame::setModifiedDate);
			attributeSetterBiConsumers.put(
				"nomeEsame", (BiConsumer<Esame, String>)Esame::setNomeEsame);
			attributeSetterBiConsumers.put(
				"dataEsame", (BiConsumer<Esame, Date>)Esame::setDataEsame);
			attributeSetterBiConsumers.put(
				"nomeInsegnante",
				(BiConsumer<Esame, String>)Esame::setNomeInsegnante);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getEsameId() {
		return _esameId;
	}

	@Override
	public void setEsameId(long esameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_esameId = esameId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getNomeEsame() {
		if (_nomeEsame == null) {
			return "";
		}
		else {
			return _nomeEsame;
		}
	}

	@Override
	public void setNomeEsame(String nomeEsame) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nomeEsame = nomeEsame;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalNomeEsame() {
		return getColumnOriginalValue("nomeEsame");
	}

	@JSON
	@Override
	public Date getDataEsame() {
		return _dataEsame;
	}

	@Override
	public void setDataEsame(Date dataEsame) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataEsame = dataEsame;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalDataEsame() {
		return getColumnOriginalValue("dataEsame");
	}

	@JSON
	@Override
	public String getNomeInsegnante() {
		if (_nomeInsegnante == null) {
			return "";
		}
		else {
			return _nomeInsegnante;
		}
	}

	@Override
	public void setNomeInsegnante(String nomeInsegnante) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nomeInsegnante = nomeInsegnante;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalNomeInsegnante() {
		return getColumnOriginalValue("nomeInsegnante");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Esame.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Esame toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Esame>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EsameImpl esameImpl = new EsameImpl();

		esameImpl.setEsameId(getEsameId());
		esameImpl.setGroupId(getGroupId());
		esameImpl.setCompanyId(getCompanyId());
		esameImpl.setUserId(getUserId());
		esameImpl.setUserName(getUserName());
		esameImpl.setCreateDate(getCreateDate());
		esameImpl.setModifiedDate(getModifiedDate());
		esameImpl.setNomeEsame(getNomeEsame());
		esameImpl.setDataEsame(getDataEsame());
		esameImpl.setNomeInsegnante(getNomeInsegnante());

		esameImpl.resetOriginalValues();

		return esameImpl;
	}

	@Override
	public Esame cloneWithOriginalValues() {
		EsameImpl esameImpl = new EsameImpl();

		esameImpl.setEsameId(this.<Long>getColumnOriginalValue("esameId"));
		esameImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		esameImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		esameImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		esameImpl.setUserName(this.<String>getColumnOriginalValue("userName"));
		esameImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		esameImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		esameImpl.setNomeEsame(
			this.<String>getColumnOriginalValue("nomeEsame"));
		esameImpl.setDataEsame(this.<Date>getColumnOriginalValue("dataEsame"));
		esameImpl.setNomeInsegnante(
			this.<String>getColumnOriginalValue("nomeInsegnante"));

		return esameImpl;
	}

	@Override
	public int compareTo(Esame esame) {
		int value = 0;

		value = getNomeEsame().compareTo(esame.getNomeEsame());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Esame)) {
			return false;
		}

		Esame esame = (Esame)object;

		long primaryKey = esame.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Esame> toCacheModel() {
		EsameCacheModel esameCacheModel = new EsameCacheModel();

		esameCacheModel.esameId = getEsameId();

		esameCacheModel.groupId = getGroupId();

		esameCacheModel.companyId = getCompanyId();

		esameCacheModel.userId = getUserId();

		esameCacheModel.userName = getUserName();

		String userName = esameCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			esameCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			esameCacheModel.createDate = createDate.getTime();
		}
		else {
			esameCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			esameCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			esameCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		esameCacheModel.nomeEsame = getNomeEsame();

		String nomeEsame = esameCacheModel.nomeEsame;

		if ((nomeEsame != null) && (nomeEsame.length() == 0)) {
			esameCacheModel.nomeEsame = null;
		}

		Date dataEsame = getDataEsame();

		if (dataEsame != null) {
			esameCacheModel.dataEsame = dataEsame.getTime();
		}
		else {
			esameCacheModel.dataEsame = Long.MIN_VALUE;
		}

		esameCacheModel.nomeInsegnante = getNomeInsegnante();

		String nomeInsegnante = esameCacheModel.nomeInsegnante;

		if ((nomeInsegnante != null) && (nomeInsegnante.length() == 0)) {
			esameCacheModel.nomeInsegnante = null;
		}

		return esameCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Esame, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Esame, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Esame, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Esame)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Esame>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Esame.class, ModelWrapper.class);

	}

	private long _esameId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _nomeEsame;
	private Date _dataEsame;
	private String _nomeInsegnante;

	public <T> T getColumnValue(String columnName) {
		Function<Esame, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Esame)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("esameId", _esameId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("nomeEsame", _nomeEsame);
		_columnOriginalValues.put("dataEsame", _dataEsame);
		_columnOriginalValues.put("nomeInsegnante", _nomeInsegnante);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("esameId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("nomeEsame", 128L);

		columnBitmasks.put("dataEsame", 256L);

		columnBitmasks.put("nomeInsegnante", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Esame _escapedModel;

}